"""
Offline AI Code Review Agent
------------------------------
Watches a folder for new/modified files.
When a change is detected, it sends the code to a local LLM (CodeLlama via Ollama)
for review — detecting changes, giving suggestions, and flagging errors.
A markdown report is saved in the /reports folder.

Requirements:
    pip install watchdog requests
    Install Ollama from https://ollama.ai
    Run: ollama pull codellama
"""

import os
import time
import requests
import hashlib
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler


WATCH_FOLDER = "./watched_code"
REPORTS_FOLDER = "./reports"
OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "codellama"
SUPPORTED_EXTENSIONS = [".py", ".js", ".ts", ".java", ".cpp", ".c", ".go", ".rb", ".php"]

os.makedirs(WATCH_FOLDER, exist_ok=True)
os.makedirs(REPORTS_FOLDER, exist_ok=True)

file_hashes = {}


def get_file_hash(filepath):
    try:
        with open(filepath, "rb") as f:
            return hashlib.md5(f.read()).hexdigest()
    except Exception:
        return None


def read_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return f"[Could not read file: {e}]"


def ask_ollama(prompt):
    try:
        response = requests.post(OLLAMA_URL, json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False
        }, timeout=120)
        response.raise_for_status()
        return response.json().get("response", "No response from model.")
    except requests.exceptions.ConnectionError:
        return "ERROR: Ollama is not running. Please start it with `ollama serve`."
    except requests.exceptions.Timeout:
        return "ERROR: Ollama took too long to respond. Try a smaller file."
    except Exception as e:
        return f"ERROR: {str(e)}"


def analyze_code(filepath, code, event_type):
    filename = os.path.basename(filepath)
    ext = os.path.splitext(filepath)[1]

    prompt = f"""You are an expert code reviewer. A developer just {event_type} a file called "{filename}".

Here is the code:

```{ext.strip(".")}
{code}
```

Please provide a thorough code review with the following sections:

1. SUMMARY OF CHANGES
   Describe what this code does and what was likely changed or added.

2. SUGGESTIONS
   List concrete improvements for code quality, readability, performance, or best practices.

3. ERRORS & BUGS DETECTED
   Identify any bugs, logical errors, potential crashes, or security issues. If none, say "No errors detected."

4. OVERALL RATING
   Give a rating out of 10 and one sentence summary.

Be specific and helpful. Format your response clearly under each numbered section.
"""

    print(f"\n  Sending to CodeLlama for analysis...")
    return ask_ollama(prompt)


def generate_report(filepath, code, analysis, event_type):
    filename = os.path.basename(filepath)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_filename = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{filename}.md"
    report_path = os.path.join(REPORTS_FOLDER, report_filename)

    lines = code.split("\n")
    report = f"""# Code Review Report

**File:** `{filename}`
**Event:** {event_type.title()}
**Date:** {timestamp}
**Lines of code:** {len(lines)}

---

## Code Reviewed

```{os.path.splitext(filepath)[1].strip(".")}
{code}
```

---

## AI Analysis

{analysis}

---

*Report generated by Offline AI Code Review Agent using CodeLlama via Ollama.*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    return report_path


def process_file(filepath, event_type):
    ext = os.path.splitext(filepath)[1].lower()
    if ext not in SUPPORTED_EXTENSIONS:
        return

    filename = os.path.basename(filepath)
    print(f"\n{'='*60}")
    print(f"  [{event_type.upper()}] {filename}")
    print(f"  Time: {datetime.now().strftime('%H:%M:%S')}")
    print(f"{'='*60}")

    code = read_file(filepath)
    if not code.strip():
        print("  Skipping empty file.")
        return

    analysis = analyze_code(filepath, code, event_type)
    report_path = generate_report(filepath, code, analysis, event_type)

    print(f"\n  Analysis complete!")
    print(f"  Report saved: {report_path}")
    print(f"\n  --- QUICK PREVIEW ---")
    preview_lines = analysis.split("\n")[:15]
    for line in preview_lines:
        print(f"  {line}")
    if len(analysis.split("\n")) > 15:
        print(f"  ... (see full report in {report_path})")


class CodeChangeHandler(FileSystemEventHandler):
    def on_created(self, event):
        if not event.is_directory:
            filepath = event.src_path
            current_hash = get_file_hash(filepath)
            file_hashes[filepath] = current_hash
            process_file(filepath, "created")

    def on_modified(self, event):
        if not event.is_directory:
            filepath = event.src_path
            current_hash = get_file_hash(filepath)
            if file_hashes.get(filepath) != current_hash:
                file_hashes[filepath] = current_hash
                process_file(filepath, "modified")


def main():
    print("\n" + "="*60)
    print("   Offline AI Code Review Agent")
    print("   Model : CodeLlama (via Ollama)")
    print(f"   Watching: {os.path.abspath(WATCH_FOLDER)}")
    print("="*60)
    print("\n  Drop any code file into the 'watched_code' folder")
    print("  and the agent will automatically review it.\n")
    print("  Press Ctrl+C to stop.\n")

    for f in os.listdir(WATCH_FOLDER):
        full = os.path.join(WATCH_FOLDER, f)
        if os.path.isfile(full):
            file_hashes[full] = get_file_hash(full)

    event_handler = CodeChangeHandler()
    observer = Observer()
    observer.schedule(event_handler, WATCH_FOLDER, recursive=True)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n\n  Agent stopped.")
        observer.stop()
    observer.join()


if __name__ == "__main__":
    main()
