"""
jenkins_agent.py
-----------------
Called directly by the Jenkinsfile in Stage 4.
Accepts changed file paths and commit info as arguments,
sends each file to CodeLlama for review, and saves a report.

Exit codes (read by Jenkins to decide pass/fail):
    0 = clean review, no critical issues
    1 = critical issues found (build marked UNSTABLE)
    2 = agent itself failed to run (build marked FAILED)
"""

import os
import sys
import argparse
import requests
from datetime import datetime


OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL      = "codellama"
REPORTS_DIR = "reports"

CRITICAL_KEYWORDS = [
    "critical", "crash", "error", "exception", "undefined",
    "null pointer", "index out of range", "division by zero",
    "security vulnerability", "infinite loop", "memory leak"
]


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--files",  required=True, help="Comma-separated list of changed file paths")
    parser.add_argument("--commit", required=True, help="Git commit hash")
    parser.add_argument("--branch", required=True, help="Git branch name")
    return parser.parse_args()


def read_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return f"[Could not read file: {e}]"


def ask_ollama(prompt):
    try:
        response = requests.post(OLLAMA_URL, json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False
        }, timeout=120)
        response.raise_for_status()
        return response.json().get("response", "No response received.")
    except requests.exceptions.ConnectionError:
        print("ERROR: Cannot connect to Ollama. Is it running? (ollama serve)")
        sys.exit(2)
    except Exception as e:
        print(f"ERROR: Ollama request failed — {e}")
        sys.exit(2)


def build_prompt(filename, ext, code, commit, branch):
    return f"""You are an expert code reviewer working inside a CI/CD pipeline.

A developer just pushed the file "{filename}" to the "{branch}" branch (commit: {commit[:8]}).

Here is the code:

```{ext}
{code}
```

Provide a structured code review with these exact sections:

1. SUMMARY
   What does this code do? What was likely changed or added?

2. SUGGESTIONS
   Specific improvements for quality, readability, or performance.

3. ERRORS & BUGS
   Any bugs, crashes, security issues, or logic errors. Include line numbers.
   If none found, write: No critical errors detected.

4. SEVERITY
   Rate the overall severity: CLEAN / LOW / MEDIUM / CRITICAL
   One line explanation.

Be direct and specific. This report will be read by a developer and their tech lead."""


def is_critical(analysis):
    text = analysis.lower()
    return any(kw in text for kw in CRITICAL_KEYWORDS) or "CRITICAL" in analysis


def save_report(filename, commit, branch, code, analysis, critical):
    os.makedirs(REPORTS_DIR, exist_ok=True)
    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_name = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{os.path.basename(filename)}.md"
    report_path = os.path.join(REPORTS_DIR, report_name)
    ext         = os.path.splitext(filename)[1].strip(".")
    status      = "CRITICAL ISSUES FOUND" if critical else "PASSED"
    status_icon = "FAIL" if critical else "PASS"

    report = f"""# Jenkins AI Code Review Report

| Field    | Value |
|----------|-------|
| Status   | {status_icon} — {status} |
| File     | `{os.path.basename(filename)}` |
| Branch   | `{branch}` |
| Commit   | `{commit[:8]}` |
| Date     | {timestamp} |
| Model    | CodeLlama (Ollama — offline) |

---

## Code Reviewed

```{ext}
{code}
```

---

## AI Analysis

{analysis}

---

*Generated by Offline AI Code Review Agent inside Jenkins CI/CD pipeline.*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"\nReport saved: {report_path}")
    return report_path


def main():
    args   = parse_args()
    files  = [f.strip() for f in args.files.split(",") if f.strip()]
    commit = args.commit
    branch = args.branch

    print(f"\n{'='*55}")
    print(f"  Jenkins AI Code Review Agent")
    print(f"  Branch : {branch}")
    print(f"  Commit : {commit[:8]}")
    print(f"  Files  : {len(files)}")
    print(f"{'='*55}\n")

    any_critical = False

    for filepath in files:
        if not os.path.exists(filepath):
            print(f"  Skipping (not found): {filepath}")
            continue

        filename = os.path.basename(filepath)
        ext      = os.path.splitext(filepath)[1].strip(".")
        code     = read_file(filepath)

        if not code.strip():
            print(f"  Skipping empty file: {filename}")
            continue

        print(f"\n  Reviewing: {filename}")
        print(f"  Sending to CodeLlama...")

        prompt   = build_prompt(filename, ext, code, commit, branch)
        analysis = ask_ollama(prompt)
        critical = is_critical(analysis)

        save_report(filepath, commit, branch, code, analysis, critical)

        status = "CRITICAL ISSUES FOUND" if critical else "CLEAN"
        print(f"  Result : {status}")

        preview = analysis.split("\n")[:8]
        print("\n  --- Preview ---")
        for line in preview:
            print(f"  {line}")
        print()

        if critical:
            any_critical = True

    print(f"\n{'='*55}")
    if any_critical:
        print("  RESULT: Critical issues found. Build → UNSTABLE")
        print(f"{'='*55}\n")
        sys.exit(1)
    else:
        print("  RESULT: No critical issues. Build → PASS")
        print(f"{'='*55}\n")
        sys.exit(0)


if __name__ == "__main__":
    main()
