"""
agent.py — Standalone offline AI code review agent
----------------------------------------------------
Watches watched_code/ for new or changed files.
Sends them to Mistral via Ollama for review.
Saves a markdown report in reports/.

Usage (local):       python3 agent.py
Usage (Docker):      runs automatically inside container
"""

import os
import time
import hashlib
import requests
from datetime import datetime
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler


WATCH_FOLDER         = "./watched_code"
REPORTS_FOLDER       = "./reports"
OLLAMA_URL           = os.getenv("OLLAMA_URL", "http://localhost:11434") + "/api/generate"
MODEL                = "mistral"
SUPPORTED_EXTENSIONS = [".py", ".js", ".ts", ".java", ".cpp", ".c", ".go", ".rb", ".php"]

os.makedirs(WATCH_FOLDER,   exist_ok=True)
os.makedirs(REPORTS_FOLDER, exist_ok=True)

file_hashes = {}


def get_file_hash(filepath):
    try:
        with open(filepath, "rb") as f:
            return hashlib.md5(f.read()).hexdigest()
    except Exception:
        return None


def read_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return f"[Could not read file: {e}]"


def ask_ollama(prompt):
    try:
        response = requests.post(OLLAMA_URL, json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False
        }, timeout=120)
        response.raise_for_status()
        return response.json().get("response", "No response from model.")
    except requests.exceptions.ConnectionError:
        return "ERROR: Cannot connect to Ollama. Is it running?"
    except requests.exceptions.Timeout:
        return "ERROR: Ollama timed out. Try a smaller file."
    except Exception as e:
        return f"ERROR: {str(e)}"


def analyze_code(filepath, code, event_type):
    filename = os.path.basename(filepath)
    ext      = os.path.splitext(filepath)[1]
    prompt   = f"""You are an expert code reviewer.
A developer just {event_type} a file called "{filename}".

Code:
```{ext.strip(".")}
{code}
```

Review with these sections:
1. SUMMARY OF CHANGES
2. SUGGESTIONS
3. ERRORS & BUGS DETECTED (with line numbers)
4. OVERALL RATING (out of 10)
"""
    print(f"\n  Sending to Mistral for analysis...")
    return ask_ollama(prompt)


def generate_report(filepath, code, analysis, event_type):
    filename    = os.path.basename(filepath)
    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_name = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{filename}.md"
    report_path = os.path.join(REPORTS_FOLDER, report_name)
    ext         = os.path.splitext(filepath)[1].strip(".")

    report = f"""# Code Review Report

**File:** `{filename}`
**Event:** {event_type.title()}
**Date:** {timestamp}
**Lines:** {len(code.splitlines())}
**Model:** Mistral via Ollama (offline)

---

## Code Reviewed

```{ext}
{code}
```

---

## AI Analysis

{analysis}

---

*Generated by Offline AI Code Review Agent*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    return report_path


def process_file(filepath, event_type):
    ext = os.path.splitext(filepath)[1].lower()
    if ext not in SUPPORTED_EXTENSIONS:
        return

    filename = os.path.basename(filepath)
    print(f"\n{'='*55}")
    print(f"  [{event_type.upper()}] {filename}")
    print(f"  Time: {datetime.now().strftime('%H:%M:%S')}")
    print(f"{'='*55}")

    code = read_file(filepath)
    if not code.strip():
        print("  Skipping empty file.")
        return

    analysis    = analyze_code(filepath, code, event_type)
    report_path = generate_report(filepath, code, analysis, event_type)

    print(f"\n  Done! Report saved: {report_path}")
    print(f"\n  --- Preview ---")
    for line in analysis.split("\n")[:10]:
        print(f"  {line}")


class CodeChangeHandler(FileSystemEventHandler):
    def on_created(self, event):
        if not event.is_directory:
            filepath = event.src_path
            file_hashes[filepath] = get_file_hash(filepath)
            process_file(filepath, "created")

    def on_modified(self, event):
        if not event.is_directory:
            filepath     = event.src_path
            current_hash = get_file_hash(filepath)
            if file_hashes.get(filepath) != current_hash:
                file_hashes[filepath] = current_hash
                process_file(filepath, "modified")


def main():
    print("\n" + "="*55)
    print("   Offline AI Code Review Agent")
    print(f"   Model   : Mistral via Ollama")
    print(f"   Watching: {os.path.abspath(WATCH_FOLDER)}")
    print("="*55)
    print("\n  Drop any code file into watched_code/")
    print("  Press Ctrl+C to stop.\n")

    for f in os.listdir(WATCH_FOLDER):
        full = os.path.join(WATCH_FOLDER, f)
        if os.path.isfile(full):
            file_hashes[full] = get_file_hash(full)

    event_handler = CodeChangeHandler()
    observer      = Observer()
    observer.schedule(event_handler, WATCH_FOLDER, recursive=True)
    observer.start()

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        print("\n\n  Agent stopped.")
        observer.stop()
    observer.join()


if __name__ == "__main__":
    main()
