"""
jenkins_agent.py
-----------------
Called by Jenkins in Stage 4 (AI Review).
Sends changed files to Mistral via Ollama.
Saves a markdown report and exits with a code Jenkins reads.

Exit codes:
    0 = clean        → build PASSES
    1 = critical     → build UNSTABLE
    2 = agent failed → build FAILED
"""

import os
import sys
import argparse
import requests
from datetime import datetime


OLLAMA_URL  = os.getenv("OLLAMA_URL", "http://localhost:11434") + "/api/generate"
MODEL       = "mistral"
REPORTS_DIR = "reports"

CRITICAL_KEYWORDS = [
    "critical", "crash", "error", "exception", "undefined",
    "null pointer", "index out of range", "division by zero",
    "security vulnerability", "infinite loop", "memory leak"
]


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--files",  required=True)
    parser.add_argument("--commit", required=True)
    parser.add_argument("--branch", required=True)
    return parser.parse_args()


def read_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return f.read()
    except Exception as e:
        return f"[Could not read file: {e}]"


def ask_ollama(prompt):
    try:
        response = requests.post(OLLAMA_URL, json={
            "model": MODEL,
            "prompt": prompt,
            "stream": False
        }, timeout=120)
        response.raise_for_status()
        return response.json().get("response", "No response.")
    except requests.exceptions.ConnectionError:
        print("ERROR: Cannot connect to Ollama.")
        sys.exit(2)
    except Exception as e:
        print(f"ERROR: {e}")
        sys.exit(2)


def build_prompt(filename, ext, code, commit, branch):
    return f"""You are an expert code reviewer inside a CI/CD pipeline.

Developer pushed "{filename}" to branch "{branch}" (commit: {commit[:8]}).

Code:
```{ext}
{code}
```

Review with these sections:
1. SUMMARY
2. SUGGESTIONS
3. ERRORS & BUGS (with line numbers, or "No critical errors detected.")
4. SEVERITY: CLEAN / LOW / MEDIUM / CRITICAL — one line reason.
"""


def is_critical(analysis):
    text = analysis.lower()
    return any(kw in text for kw in CRITICAL_KEYWORDS) or "CRITICAL" in analysis


def save_report(filepath, commit, branch, code, analysis, critical):
    os.makedirs(REPORTS_DIR, exist_ok=True)
    timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_name = f"{datetime.now().strftime('%Y%m%d_%H%M%S')}_{os.path.basename(filepath)}.md"
    report_path = os.path.join(REPORTS_DIR, report_name)
    ext         = os.path.splitext(filepath)[1].strip(".")
    status      = "FAIL — CRITICAL ISSUES" if critical else "PASS — CLEAN"

    report = f"""# Jenkins AI Code Review Report

| Field   | Value |
|---------|-------|
| Status  | {status} |
| File    | `{os.path.basename(filepath)}` |
| Branch  | `{branch}` |
| Commit  | `{commit[:8]}` |
| Date    | {timestamp} |
| Model   | Mistral via Ollama (offline) |

---

## Code Reviewed

```{ext}
{code}
```

---

## AI Analysis

{analysis}

---

*Generated by Offline AI Code Review Agent — Jenkins Pipeline*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"\n  Report saved: {report_path}")
    return report_path


def main():
    args   = parse_args()
    files  = [f.strip() for f in args.files.split(",") if f.strip()]
    commit = args.commit
    branch = args.branch

    print(f"\n{'='*55}")
    print(f"  Jenkins AI Code Review Agent")
    print(f"  Model  : Mistral (Ollama — offline)")
    print(f"  Branch : {branch}")
    print(f"  Commit : {commit[:8]}")
    print(f"  Files  : {len(files)}")
    print(f"{'='*55}\n")

    any_critical = False

    for filepath in files:
        if not os.path.exists(filepath):
            print(f"  Skipping (not found): {filepath}")
            continue

        filename = os.path.basename(filepath)
        ext      = os.path.splitext(filepath)[1].strip(".")
        code     = read_file(filepath)

        if not code.strip():
            print(f"  Skipping empty file: {filename}")
            continue

        print(f"  Reviewing : {filename}")
        print(f"  Sending to Mistral...")

        prompt   = build_prompt(filename, ext, code, commit, branch)
        analysis = ask_ollama(prompt)
        critical = is_critical(analysis)

        save_report(filepath, commit, branch, code, analysis, critical)
        print(f"  Result    : {'CRITICAL ISSUES FOUND' if critical else 'CLEAN'}")

        for line in analysis.split("\n")[:8]:
            print(f"  {line}")

        if critical:
            any_critical = True

    print(f"\n{'='*55}")
    if any_critical:
        print("  FINAL: Critical issues found — Build UNSTABLE")
        sys.exit(1)
    else:
        print("  FINAL: No critical issues — Build PASSED")
        sys.exit(0)


if __name__ == "__main__":
    main()
